---
title: "second-post"
categories: [blog]
---

화요일에 선수과목 \< R 프로그래밍 입문 \> 과 \< 기초통계학 \> 시험을 봤다. 금요일부터는 시험 당일까지 서너 시간만 자면서 밤을 샜다. 시험을 잘 보고 싶은데 잘 될 것 같지 않아서 애가 탔다. 같은 반 동기들 중에는 기존에 R을 약간이라도 써 본 경험이 있거나 아예 통계학을 부전공한 경우도 더러 있어서 몹시 걱정스러웠다(왜냐면 나는 둘 다 전혀 아니었으니까). 이번 시험은 pass/fail 여부만 남지만 그래도 중간 이상은 하고 싶었는데.. 신기했던 것은 언젠가 만들어진 자료 공유용 구글 드라이브에 너도 나도 할 것 없이 자신의 필기나 강의 요약본, 각자 공부하면서 도움이 되었던 자료들을 기꺼이 공유하는 동기들의 모습이었다. 그룹챗에서는 어떤 문제가 나올까 서로 예측해보기도 하면서 각자가 이해하고 있는 방식이나 단계 정도를 예측할 수 있었다. 이런 분위기나 문화가 여기에서는 얼마나 자연스러운 것인지 모르겠으나 시험이라면 상대평가가 전부인 시스템 아래에서 자란 나로서는 꽤 신선하고 긍정적인 충격이었다.

이 자료 공유가 없었다면 상상만 해도 아찔한 것이 시험 전날 새벽 누군가 작년에 같은 교수님의 \< R 프로그래밍 입문 \> 수업을 들었던 지인으로부터 받은 기출문제를 공유했다. 자료에는 dataset부터 문제, 코딩 답안이 전부 포함되어 있었는데 올해 시험에서도 동일한 dataset을 썼고 총 여덟 문제 중 다섯 문제가 거의 동일했다. 완전한 오픈북 시험이긴 했지만 (강의 슬라이드, 필기 내용, 구글링, chatGPT 등 AI 사용까지 모두 가능했다. 이게 가능했던 것은 12시간 동안 다룬 함수의 종류가 워낙 한정적이다 보니 작성한 코드만 봐도 강의한 내용에 기초해서 본인이 오롯이 풀었는지 아니면 어디에 기대서 풀었는지 너무 쉽게 눈에 띄었기 때문이다. 물론 이게 pass/fail을 위한 선수과목이라는 특성상 다른 것에 기대서 풀었다고 해서 점수에 영향이 있는 것도 아니었다.) 그래도 내가 작년 기출문제를 풀지 않았더라면 그 다섯 문제들을 그렇게 빨리 풀 수 있었을까 싶었고.. 남은 세 문제 중에서는 한 문제를 제대로 풀지 못하고 답안을 제출했다.

\< 기초 통계학 \> 시험은 우리 모두를 식겁하게 만들었다. A4용지 한 면에 수기로 작성한 cheat-sheet와 계산기만 허용되는 수기 시험이었는데 총 여섯 문제가 나왔다. 각 문제는 두 개부터 여섯 개 정도 되는 하위 문제로 구성되어 있었다. 시험을 마치고 건물 앞에 우르르 모인 우리들 사이로 나타난 교수님께서는 '문제가 정말 쉽지 않았냐'고 하셨지만 (너스레의 느낌이 전혀 아니었음. - 우리에 대한 기대치가 높으셨거나 또는 과대평가를 하신 것이 분명하게도 - 교수님은 그저 순수한 마음으로 그렇게 말하신 것 같았다.) 정말이지 대부분 fail을 걱정하고 있었다. 가장 쉬웠던 다양한 통계량을 계산하는 첫번째 문제는 숫자가 딱 떨어지지 않아서 '이게 맞나..?'하면서 시간을 꽤 많이 쓰게 되었고 어떤 문제는 도저히 함수로 풀이를 적을 자신이 없어서 그림을(?) 그렸다. 두 문제는 아예 아무런 답을 못 적어냈다. 갑갑했다. 교수님들은 '최악의 경우라고 해도 재시험을 보는 수준이다'고 하셨지만.. 재시험은 둘째 치고 내가 다음 통계학 수업을 잘 따라갈 수 있을까 겁이 났다.

\< R 프로그래밍 입문 \> 점수는 예상보다 빨리 목요일 아침에 나왔다. 100점 만점 중에 86점. 제대로 풀지 못한 문제 하나로 10점이 깎이고 풀이 중에 실수를 한 함수가 하나 있어서 4점이 차등 감점되지 않았나 싶다. 개별 코멘트를 받은 학생 한두 명은 수업이 끝나고 찾아오길 바란다는 교수님을 말을 보아서도, 프로그래밍 수업에 온 친구들의 표정만 보아서도 다들 큰 무리 없이 괜찮은 점수를 받은 것 같았다. 이번주가 다 가도록 \< 기초 통계학 \> 점수는 아직 나오지 않았으니 월요일까지 기다려 봐야 할 듯 싶다.

여하튼 선수과목 일정은 이렇게 시험으로 끝이 났고 곧장 9월 10일 수요일부터 1학기 개강을 했다. \< 데이터 시각화(Data Visualization) \>, \< 데이터 프로그래밍(Data Programming) \>, \< 전산사회과학의 기초(Foundation of Computational Social Science) \> 세 과목의 첫 수업이 있었다. R로 이렇게 많은 것을 할 수 있는 줄 정말 몰랐고 드디어 수학이 아닌 사회과학의 영역에 있는 주제들을 다루는 수업이 시작되어서 모두가 눈을 반짝였다. 물론 온갖 과제와 시험 일정도 함께 쏟아졌다. 개인 프로젝트, 페이퍼, 코딩 과제, 조별 발표 등으로 종류가 다양했다. 다음주에 두 과목 개강이 더 기다리고 있으니까 정신을 똑바로 차려야겠다고 생각했다. 학비를 일 년만 내서 좋았는데.. 몸과 뇌는 두 배 정도 더 고생하는 코스였다는 것을 새삼 깨달았다.

금요일에는 학과 웰컴 이벤트가 있었다. 감각을 통한 신체 인식에 대한 연구를 하신 교수님께서 40분 정도 간단한 강연을 해주셨고 나머지 시간에는 지하 카페테리아에서 다과 시간을 가졌다. 분명 이메일에는 '칵테일'이라고 했지만 각종 논알콜 소프트 드링크와 각종 치즈, 크래커, 보까디요, 컵과일 등 전형적인 현지 핑거푸드로 구성되어 있었다. 벌써 개강하고 2주가 끝났으니 거의 대부분과 안면이 있었지만 처음 말을 나눠보는 동기들도 있었다. 이탈리아, 호주, 시리아, 대만, 미국, 칠레, 아르헨티나, 터키 등 생각보다 다른 나라에서 오직 이 코스를 위해 마드리드에 온 국제학생들이 정말 많았고, 현재 재직자이거나 풀타임으로 일해 본 경험이 있는 경우는 열 명이 채 안 되는 것 같았다. 보통 스물셋, 스물넷 - 학부를 마치고서 바로 또는 갭이어를 잠시 가지고 온 경우였다.

회사를 다닐 때는 주로 다음 휴가지와 요즘 열심히 하고 있는 운동에 대해서 이야기했다. 대출을 껴서 집을 사고 싶은데 언제까지 기다려야할지 모르겠다거나 결혼 준비에 대책 없이 돈을 얼마나 쏟아붓고 있는지 걱정했고 일이 많아서 치일 때에는 다음 연봉협상까지 기다려보자며 서로를 응원했다. 여기에서는 아무도 그런 이야기를 하지 않았다. 동기들은 생각보다 학교 런치메뉴가 저렴하지 않다고 얘기했고 유명한 체인 샐러드 카페에 가서 저녁을 먹고 싶어했으며 주말에는 무료로 갈 수 있는 근교도시들에 대한 계획을 나누고 있었다. 상반된 감정이 동시에 일었다. '해봐야 알지 않냐'며 제법 치기 어린 생각으로 이십대 내내 열심히도 헤매고, 눈에 차고 손에 닿을 만한 것들 사이에서 크고 작은 결정들을 내리며, 한편으로는 큰 돈이지만 또 어쩌면 아무것도 아닌 돈을 모아, 간신히 스물아홉이 되어서야 나는 도착한 곳이니까. 누군가에게는 그저 짧게 스쳐 지나갈 이 도시가 나에게는 새로이 살아가기로 선택한 공간이고, 또 누군가에게는 그저 학부의 연장선일지 모르는 이 코스가 나에게는 버젓한 직장을 그만두고 선택한 일종의 절박함이니까. 그럼에도 나는 내가 그 모든 일을 하나하나 겪어온 것들이 전혀 아쉽지도 부끄럽지도 않다. 조금 늦은 것 같아보여도 그래서 천천히 여기까지 온 것이 자랑스럽다. 그리고 이렇게 내 과거와 현재를 긍정하는 일이 곧 내 미래를 긍정하는 것과 맞닿아 있을 거라고 굳게 믿는다.
