---
title: "W3 | 3주만에 드디어 정상 궤도 안착!"
categories: [blog]
---

정신없이 선수과목 수강과 시험을 해치우고 신체적으로도 심리적으로도 훨씬 안정되었던 개강 3주차. 이제 (무려) 졸업 전까지 금요일 수업은 전혀 없고 월요일 수업도 딱 두 번 남아있다. 화/수/목 3일 동안 바짝 몰아서 수업을 듣고, 남은 4일 동안은 각자 공부하고 과제하고 나중에는 논문을 쓰면서 보내는 진짜 정상 궤도에 안착한 셈이다. 인풋은 쏟아지다시피 밀어닥치는데, 추천해주신 자료들도 읽어보고 수업 시간 동안 새로이 배운 것도 다시 살펴보며 그것들을 '내 것'으로 만들 시간이 거의 없었던 게 사실 너무 불안했는데.. 일단 물리적인 시간이 선명하게 늘어나 그게 무엇이든 계획하고 실행해볼 여지가 생긴 것 같아 기뻤다.

주중에 파트너가 집을 잠시 비웠기 때문에 꽤 오랜만에 혼자 일상을 꾸렸다. 운동-도서관-수업 밖에 없는 단조로운 패턴에도 불구하고, 끼니를 잘 챙기고 잡다한 일들로 손이 많이 가는 집을 돌보며 한 사람이 맡고 있던 몫이 생각보다 얼마나 큰지 새삼 깨닫게 되었다. (사실 2인 가구니까 한 사람만 자리를 비워도 50%가 비는 셈이다!) 대신 혼자 훌훌 돌아다니며 소소한 기쁨도 톡톡히 누렸다. 늦여름과 가을 초입 그 어딘가에 서 있는 9월 중순의 마드리드는 특별할 것이 아무것도 없어도 저절로 행복해지는 때이니까. 고작 3주차이면서 벌써 농땡이인가 싶지만도, 코딩이고 통계학이고 머리가 어질어질해질 때 즈음 도서관으로 가던 발걸음을 돌려 곧내 좋아하는 카페에서 여유로이 종이책을 읽다보면 그냥 이런 시간을 내킬 때마다 고민없이 가질 수 있다는 것만으로 나는 충분하게 행복하다고 소리내어 말하고 싶어졌다. 또 한편으로는 거의 하루 종일 랩탑이나 태블릿 화면을 쳐다보고 있으니 어디에선가 균형을 맞춰야 한다는 내 안의 외침(!)이 들리면서 자꾸만 종이책에 대한 열망도 커져가는 중이고.

\< 통계와 데이터 사이언스 I(Statistics and Data Science I) \>, \< 사회과학을 위한 연구설계(Research Design for Social Sciences) \> 두 과목까지 포함해 본격적으로 첫 쿼터 동안의 모든 과목이 시작된 주였다. 총 다섯 과목으로 이론 1, 통계학 1, R 프로그래밍 2, 모델링 1로 대강 나눠볼 수도 있겠다. 두 쿼터 동안 더 긴 시간 동안 다루는 과목들도 있고 한 쿼터만에 끝나는 과목들도 있다. 한 쿼터가 대략 7회 세션이니까 21시간 만에 한 과목을 아주 집약적으로 배우게 되는 셈이다. 물론 해당 기간 동안 평가를 위한 과제와 시험, 발표, 페이퍼 같은 것들도 모두 포함된다. 동기들은 그룹챗에 각자가 정리한 스케줄표를 공유하면서도 두 번이고 세 번이고 놓친 게 없는지 확인하고 있다. 참, 선수과목을 포함해 그동안 총 여섯 분의 교수님을 만났는데 한 분을 제외하고 모두가 30대 초중반이라는 사실에 꽤 놀라기도 했다(나도 내년이면 서른인데...?) 스페인의 학제나 시스템 어딘가가 한국과는 확연히 다른 것인지 아니면 내가 그동안 내려온 선택들이 일련의 공통점을 갖고 이어지고 있는 것인지는 모르겠으나 직장이며 학교며 그동안 내가 스페인에서 머무른 모든 공간을 채우는 사람들의 평균 연령이 모두 다 낮은 편인 것 같다.

일상이 조금씩 제 자리를 찾아가면서 공부하는 시간을 조금씩 늘리고 루틴을 잡으려고 노력하고 있다. 제일 우선순위에 있는 것은 첫째, 헬스장/러닝/요가 등 종류에 관계없이 매일 운동하기 (걷기X) 그리고 둘째, 매일 한 시간 코딩연습. 또 회사 다닐 때처럼 앉아있는 시간이 기하급수적으로 늘어나는데 반짝 날씨 좋고 기분 좋고 시즌이 지나면 겨울에 체력거지(!)가 되어있을 모습이 눈에 선하고, 또 계속해서 중요한 이벤트들이 줄줄이 기다리고 있기도 하니까 언젠가부터 늘 그래왔듯이 운동은 늘 우선순위에. 하지만 아침마다 온갖 핑계거리를 찾는 걸 보니 아직도 한참 멀었고.. 분발하자(먼산). 석사과정 중에 SQL과 파이썬도 조금 다룬다고 들었지만 70% 이상은 R을 사용하는 것 같은데 이건 매일매일 하는 게 제일 스트레스 덜 받고 빨리 느는 길인 것 같아서 시작한 코딩연습은 다행히 무난하게 정착해가고 있다.

주말에는 오랜만에 커피챗이 두 건 있었다. 이따금씩 커피챗 요청을 받는데 사실상 가장 최근에 퇴사한 회사와 연결된 경우일 때가 많았다. 특히 근무 중일 때에는 지원을 앞두고 회사 분위기와 특정 포지션에 대해 현직자의 의견이 궁금해서, 조금 나아가서는 리퍼럴을 요청해보기 위해서 온 커피챗이 대부분이었다. 가끔은 (이번 주말처럼) 스페인에서 한국인, 그러니까 외국인으로서 처음 마케팅 분야 취업을 시도하는 것과 관련된 경험을 듣기 위한 커피챗 요청이 오기도 한다. 지금의 나는 마케팅과 한 발 떨어져 있지만 그래도 여전히 링크드인이나 CV 속 나는 마케터이니까. 나도 사실 특별하다 할 만한 전략이 별로 없었지만, 그리고 여전히 어느 정도는 내가 열심히 지원을 할 시기의 취업시장에 내가 갈 만한 포지션이 있는가 없는가 하는 운의 영역이라고 생각하지만, 그래도 내가 당시에 넘어지고 울고 좌절하면서 시도했던 일들, 그렇게 몸으로 배웠던 것들에 대해서 얘기한다. 우리 모두의 상황이 각기각색으로 다르듯 천편일률적으로 통하는 팁 같은 것들은 사실 없다는 걸 알지만 그래도 하나의 실마리라도 찾기를 바라는 절박함을 잘 알기 때문이다.

매번 커피챗을 할 때마다 '내가 가진 것들에 하나라도 더 추가해야 하는' 또 '가진 것들을 잘 보여주기 위해 노력해야 하는' 그 시기가 얼마나 심리적으로 어렵고 또 고통스러운지 다시 느낀다. 나도 나름대로 부단히 노력했지만 그래도 그 때에 운이 따라주어서 다행이라고 숨을 뱉어본다. 이 공부가 끝나면 또 완전히 모르는 세상에서 취업을 준비해야 할 때가 올 텐데. 스페인 살이 4년차, 마케터 5년차가 되어서야 보이는 것이 있었듯 어떤 출발점에서는 미처 볼 수 없는 것들이 분명히 있을 것이다. 그래도 나에 대해서만큼 더 많이 알게 되었을 테고 그게 어떤 길잡이가 되어줄 거라고 믿어보는 수밖에.
